[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/dist"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/dist/404.html"
  status = 404
  force = true

