[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1" }
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["full"] }
log = "0.4.25"
env_logger = "0.11.6"
